module.exports = [
  {
    item_name: "Income",
    amount: 1159.0,
    date: "June 07, 2020",
    from: "Psaal Store",
    category: "income",
  },
  {
    item_name: "Food",
    amount: -300,
    date: "June 09, 2021",
    from: "Pet Store",
    category: "Food",
  },
  {
    item_name: "Savings",
    amount: -200,
    date: "September 21, 2021",
    from: "Retirement",
    category: "savings",
  },
  {
    item_name: "Income",
    amount: 4100,
    date: "December 19, 2021",
    from: "Savings",
    category: "Income",
  },
  {
    item_name: "Television",
    amount: -100,
    date: "August 11, 2021",
    from: "Credit Card Payment",
    category: "Bank",
  },
  {
    item_name: "Parrot",
    amount: 20,
    date: "November 21, 2022",
    from: "Pasaal Store",
    category: "Pet",
  },
  {
    item_name: "Cat Food",
    amount: -4,
    date: "October 01, 2020",
    from: "Pet Store",
    category: "Food",
  },
  {
    item_name: "Router",
    amount: -100,
    date: "February 13, 2022",
    from: "Cisco",
    category: "Telecoms",
  },
  {
    item_name: "Popcorn",
    amount: -76,
    date: "March 21, 2020",
    from: "Groceries",
    category: "Food",
  },
  {
    item_name: "Multiplexers",
    amount: -4500,
    date: "April 05, 2021",
    from: "Pet Food",
    category: "Telecoms",
  },
];
